<?php

use PokemonGoLingen\PogoAPI\Collections\TranslationCollection;
use PokemonGoLingen\PogoAPI\Renderer\RaidBossGraphicConfig;
use PokemonGoLingen\PogoAPI\Types\RaidBoss;
if (!isset($bosses)) {
    $bosses = [];
}
if (!isset($translationCollection)) {
    $translationCollection = new TranslationCollection('');
}

if (!isset($raidBossGraphicConfig)) {
    $raidBossGraphicConfig = new RaidBossGraphicConfig();
}

$svgWidth = 985;
$width               = 685;
$maxCounterInRow     = 7;
$lineHeight          = 50;
$graphicHeaderHeight = 30;
$graphicFooterHeight = 10;
$totalHeight = ($lineHeight * count($bosses)) + $graphicHeaderHeight + $graphicFooterHeight;
$svgHeight = intval($totalHeight * ($svgWidth / $width));

$renderWeatherIcon = function(string $weatherIcon, int $x): string {
    $y = 12;
    $width = $height = 25;

    switch ($weatherIcon) {
        case 'rain':
        case 'cloudy':
        case 'partlycloudy_day':
            $x -= 5;
            $y -= 5;
            $width = $height += 10;
            break;
    }

    return <<<SVG
    <image x="{$x}" y="{$y}" width="{$width}" height="{$height}" class="pokemon-type-icon" href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Weather/weatherIcon_small_{$weatherIcon}.png">
        <title>{$weatherIcon}</title>
    </image>  
    SVG;
};

$renderBossName = function(object $boss): string {
    $bossName = $boss->name;
    $explodedName = [];

    if (strpos($bossName, ' ') !== false) {
        $explodedName = explode(' ', $bossName, 2);
    } else if (strpos($bossName, '-') !== false) {
        $explodedName = explode('-', $bossName, 2);
    }

    $firstLineSmall = true;
    if (count($explodedName) === 2 && strpos($explodedName[1], '(') === 0) {
        $firstLineSmall = false;
    }

    if (count($explodedName) === 2) {
        $tspan1Class = $firstLineSmall ? 'small' : '';
        $tspan2Class = $firstLineSmall ? '' : 'small';

        return <<<SVG
        <text text-anchor="end" x="295" y="35" class="double-line">
            <tspan class="{$tspan1Class}" x="295" y="22">{$explodedName[0]}</tspan><tspan class="{$tspan2Class}" x="295" y="44">{$explodedName[1]}</tspan>
        </text>
        SVG;
    }

    return <<<SVG
    <text text-anchor="end" x="295" y="35">{$bossName}</text>
    SVG;
};

echo '<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>';
?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 <?=$width?> <?=$totalHeight?>" width="<?=$svgWidth?>"
     preserveAspectRatio="none" version="1.1">
    <style>
        .boss-types rect,
        .boss-level rect,
        .boss-cp-spectrum rect {
            opacity: 0.4;
            fill: #ccc;
        }

        .boss-image rect,
        .boss-name rect,
        .boss-weather rect,
        .boss-counter rect {
            opacity: 0;
            fill: #f00;
        }

        .pokemon-type-icon {
            filter: drop-shadow(0px 0px 1px rgba(255, 255, 255, 0.7));
        }

        .boss-level {
            fill: #ddd;
            font-size: 18px;
            font-family: sans-serif;
            dominant-baseline: middle;
            text-anchor: middle;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
        }

        .boss-name text {
            font-size: 24px;
            line-height: 1.25;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-transform: uppercase;
        }

        .boss-name text tspan.small {
            font-size: 14px;
        }

        .boss-cp-spectrum text {
            font-size: 13px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
        }

        .boss-counter text {
            font-size: 9px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
        }
        .boss-counter .double-damage {
            fill: #fc684e;
        }

        .boss-counter .image-counter-256 {
            filter: drop-shadow(0px 0px 3px rgba(0, 0, 0, 0.6));
        }

        .boss-cp-spectrum .boost {
            fill: #ccc;
        }

        .graphic-header text {
            font-size: 10px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-transform: uppercase;
            text-anchor: middle;
        }

        .graphic-header line {
            stroke: #ffffff;
            stroke-width: 1;
        }

        .source-url {
            fill: #fff;
            font-size: 8px;
            font-family: sans-serif;
            text-anchor: middle;
        }
    </style>
    <defs>
        <linearGradient id="header" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#000"/>
            <stop offset="100%" stop-color="#333"/>
        </linearGradient>
        <linearGradient id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_EX ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#000"/>
            <stop offset="100%" stop-color="#333"/> <!-- lighten 20% -->
        </linearGradient>
        <linearGradient id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_MEGA ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#8e3628"/>
            <stop offset="100%" stop-color="#c14936"/> <!-- lighten 20% -->
        </linearGradient>
        <linearGradient id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_5 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#3f577c"/>
            <stop offset="100%" stop-color="#6c89b4"/> <!-- lighten 40% -->
        </linearGradient>
        <linearGradient id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_3 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#806b2e"/>
            <stop offset="100%" stop-color="#b1943f"/> <!-- lighten 20% -->
        </linearGradient>
        <linearGradient id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_1 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#870f52"/>
            <stop offset="100%" stop-color="#b7146f"/> <!-- lighten 15% -->
        </linearGradient>
    </defs>

    <g class="graphic-header">
        <rect fill="url('#header')" width="<?=$width?>" height="<?= $graphicHeaderHeight ?>" x="0" y="0"/>
        <line x1="0" x2="<?=$width?>" y1="<?= $graphicHeaderHeight ?>" y2="<?= $graphicHeaderHeight ?>"/>
        <text x="18" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_level')?></text>
        <text x="185" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_boss')?></text>
        <text x="335" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_type')?></text>
        <text x="400" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_weather')?></text>
        <text x="470" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_cprange')?></text>
        <text x="590" y="20"><?=$translationCollection->getCustomTranslation('raidgraphic_header_counter')?></text>
    </g>

    <g class="graphic-footer">
        <rect fill="#000" width="<?=$width?>" height="<?= $graphicFooterHeight ?>" x="0" y="<?=$totalHeight-$graphicFooterHeight?>"/>
        <text class="source-url" x="<?=round($width/2)?>" y="<?=$totalHeight-2?>">Raidboss source from leekduck.com | generated for pokemon-go-lingen.github.io/pokemon-go-api/ | Image Source by The Pokemon Company and Niantic</text>
    </g>

    <?php foreach ($bosses as $index => $boss) : ?>
        <svg id="raidbosswrapper-<?= $boss->id ?>" x="0" y="<?= $index * $lineHeight + $graphicHeaderHeight ?>" width="100%" height="<?= $lineHeight + 10 ?>">
            <rect fill="url('#raidBossGradient_<?= $boss->level ?>')" width="100%" height="<?= $lineHeight ?>" x="0" y="0"/>

            <g class="boss-level">
                <rect width="35" height="<?= $lineHeight ?>" x="0" y="0"/>
                <image height="36" width="36" x="0" y="12" href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Raids/raid_egg_<?=$boss->levelIcon?>_icon_notification.png" />
            </g>

            <g class="boss-name">
                <rect width="215" height="<?= $lineHeight ?>" x="85" y="0"/>
                <?= $renderBossName($boss) ?>
            </g>

            <g class="boss-image">
                <rect width="50" height="<?= $lineHeight ?>" x="35" y="0"/>

                <image width="55" height="55" x="25" y="0"
                       href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Pokemon/<?= $boss->image . ($boss->shiny && $raidBossGraphicConfig->useShinyImages() ? '_shiny' : '') ?>.png"/>
                <?php if ($boss->shiny) : ?>
                    <image class="boss-shiny-image" width="15" height="15" x="22" y="0"
                           href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Filters/ic_shiny_white.png"/>
                <?php endif; ?>
            </g>

            <g class="boss-types">
                <rect width="70" height="<?= $lineHeight ?>" x="300" y="0"/>
                <svg width="70" height="<?= $lineHeight?>" x="300" y="0">
                <?php if (count($boss->types) === 1) : ?>
                    <image x="22" y="12" width="26" height="26" class="pokemon-type-icon"
                           href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Types/POKEMON_TYPE_<?= strtoupper($boss->types[0]) ?>.png">
                        <title><?=$boss->types[0]?></title>
                    </image>
                <?php else : ?>
                    <image x="7" y="12" width="26" height="26" class="pokemon-type-icon"
                           href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Types/POKEMON_TYPE_<?= strtoupper($boss->types[0]) ?>.png">
                        <title><?=$boss->types[0]?></title>
                    </image>
                    <image x="38" y="12" width="26" height="26" class="pokemon-type-icon"
                           href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Types/POKEMON_TYPE_<?= strtoupper($boss->types[1]) ?>.png">
                        <title><?=$boss->types[1]?></title>
                    </image>
                <?php endif; ?>
                </svg>
            </g>

            <g class="boss-weather">
                <rect width="60" height="<?= $lineHeight ?>" x="370" y="0"/>
                <svg width="60" height="<?= $lineHeight?>" x="370" y="0">
                <?php if (count($boss->weather) === 1) {
                    echo $renderWeatherIcon($boss->weather[0], 17);
                } else {
                    echo $renderWeatherIcon($boss->weather[0], 5);
                    echo $renderWeatherIcon($boss->weather[1], 30);
                }
                ?>
                </svg>
            </g>

            <g class="boss-cp-spectrum">
                <rect width="80" height="<?= $lineHeight ?>" x="430" y="0"/>
                <svg width="80" height="<?= $lineHeight?>" x="430" y="0">
                    <text class="normal" x="50%" y="18" dominant-baseline="middle" text-anchor="middle"><?= $boss->cpRange ?></text>
                    <text class="boost"  x="50%" y="35" dominant-baseline="middle" text-anchor="middle"><?= $boss->cpRangeBoost ?></text>
                </svg>
            </g>

            <g class="boss-counter">
                <rect width="160" height="<?= $lineHeight ?>" x="510" y="0"/>
                <svg width="160" height="<?= $lineHeight ?>" x="510" y="0" >
                    <?php
                    $counterTypeIndex = count($boss->counter) - 1;
                    foreach ($boss->counter as $type => $multiplier) :
                        $x              = 10 + ($counterTypeIndex * 20) + (($maxCounterInRow - count($boss->counter)) * 10);
                        $multiplierText = str_replace('.', '', $multiplier);
                        ?>
                        <image class="image-counter-<?=$multiplierText?>" x="<?= $x ?>" y="12" width="24" height="24"
                               href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Types/POKEMON_TYPE_<?= strtoupper($type) ?>.png">
                            <title><?=$type . ' ' . $multiplier?></title>
                        </image>
                        <?php
                        if ($multiplier > 2) : ?>
                            <circle class="double-damage" r="8" cx="<?=$x + 2?>" cy="36" />
                            <text x="<?= $x - 4 ?>" y="39">2x</text>
                        <?php
                        endif;
                        $counterTypeIndex--;
                    endforeach;

                    ?>
                </svg>
            </g>

        </svg>
    <?php endforeach;
    ?>
</svg>