<?php

use PokemonGoApi\PogoAPI\Collections\TranslationCollection;
use PokemonGoApi\PogoAPI\Renderer\Types\RaidBossGraphicConfig;
use PokemonGoApi\PogoAPI\Renderer\Types\RenderingRaidBoss;
use PokemonGoApi\PogoAPI\Types\RaidBoss;
use PokemonGoApi\PogoAPI\Types\WeatherBoost;

/** @var $bosses array<int, RenderingRaidBoss> */
if (!isset($bosses)) {
    $bosses = [];
}
if (!isset($translationCollection)) {
    $translationCollection = new TranslationCollection('');
}

if (!isset($raidBossGraphicConfig)) {
    $raidBossGraphicConfig = new RaidBossGraphicConfig();
}

if ($raidBossGraphicConfig->getOrder() === RaidBossGraphicConfig::ORDER_LVL1_TO_MEGA) {
    $bosses = array_reverse($bosses);
}

// reverse with preserve key to render the graphic from the bottom to the top
$bosses = array_reverse($bosses, true);

$svgWidth            = 1080;
$width               = 780;
$maxCounterInRow     = 7;
$lineHeight          = 50;
$graphicHeaderHeight = 80;
$graphicFooterHeight = 10;
$totalHeight = ($lineHeight * count($bosses)) + $graphicHeaderHeight + $graphicFooterHeight;
$svgHeight = (int)($totalHeight * ($svgWidth / $width));

$renderWeatherIcon = static function(RenderingRaidBoss $raidBoss): string {
    $getWeatherSize = static function (int $x, WeatherBoost $weatherBoost): string {
        $y = 14;
        $width = $height = 22;
        switch ($weatherBoost->getWeather()) {
            case WeatherBoost::RAIN:
                $width = $height += 12;
                $y -= 5;
                $x -= 5;
                break;
        }

        return sprintf('x="%d" y="%d" width="%d" height="%d"', $x, $y, $width, $height);
    };
    $weatherBoosts = $raidBoss->getWeatherBoost();

    if (count($weatherBoosts) === 1) {
        return <<<SVG
        <image {$getWeatherSize(19, $weatherBoosts[0])} class="pokemon-type-icon" href="{$raidBoss->getWeatherIconUrl($weatherBoosts[0])}"></image>
        SVG;
    }

    return <<<SVG
    <image {$getWeatherSize(5, $weatherBoosts[0])} class="pokemon-type-icon" href="{$raidBoss->getWeatherIconUrl($weatherBoosts[0])}"></image>
    <image {$getWeatherSize(32, $weatherBoosts[1])} class="pokemon-type-icon" href="{$raidBoss->getWeatherIconUrl($weatherBoosts[1])}"></image>
    SVG;

};

// use with echo because of PHP short open syntax <?
echo '<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>';
?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
     viewBox="0 0 <?=$width?> <?=$totalHeight?>" width="<?=$svgWidth?>"
     preserveAspectRatio="none" version="1.1">
    <style>
        .boss-types rect,
        .boss-level rect,
        .boss-difficulty > rect,
        .boss-cp-spectrum rect {
            opacity: 0.4;
            fill: #ccc;
        }

        .boss-image rect,
        .boss-name rect,
        .boss-weather rect,
        .boss-counter rect {
            opacity: 0;
            fill: #f00;
        }

        .pokemon-type-icon {
            filter: drop-shadow(0px 0px 1px rgba(255, 255, 255, 0.7));
        }

        .boss-level {
            fill: #ddd;
            font-size: 18px;
            font-family: sans-serif;
            dominant-baseline: middle;
            text-anchor: middle;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
        }

        .boss-name text {
            font-size: 24px;
            line-height: 1.25;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-transform: uppercase;
        }

        .boss-name text tspan.small {
            font-size: 14px;
        }

        .boss-cp-spectrum text {
            font-size: 13px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-anchor: middle;
            dominant-baseline: middle;
        }

        .boss-counter text {
            font-size: 9px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
        }
        .boss-counter .double-damage {
            fill: #fc684e;
        }

        .boss-counter .image-counter-256 {
            filter: drop-shadow(0px 0px 3px rgba(0, 0, 0, 0.6));
        }

        .boss-cp-spectrum .boost {
            fill: #ccc;
        }

        .boss-difficulty text {
            font-size: 16px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-anchor: middle;
            dominant-baseline: middle;
        }

        .boss-difficulty .mode-easy rect {
            fill: #393;
        }
        .boss-difficulty .mode-normal rect {
            fill: #fc0;
        }
        .boss-difficulty .mode-hard rect {
            fill: #a00;
        }

        .graphic-header div {
            font-family: sans-serif;
            color: #ffffff;
            margin: 0;
            text-align: right;
            font-size: 9px;
        }

        .graphic-header div > p {
            margin: 3px 0 0 0;
            font-style: italic;
        }

        .graphic-header div .circle {
            display: inline-block;
            border-radius: 4px;
            padding: 0 2px;
            font-size: 10px;
        }

        .graphic-header div .circle.mode-easy {
            background-color: #393;
        }
        .graphic-header div .circle.mode-normal {
            background-color: #fc0;
        }
        .graphic-header div .circle.mode-hard {
            background-color: #a00;
        }

        .graphic-header .title-header text {
            font-size: 10px;
            font-family: sans-serif;
            fill: #ffffff;
            filter: drop-shadow(1px 1px 1px rgba(0, 0, 0, 0.6));
            text-transform: uppercase;
            text-anchor: middle;
        }

        .graphic-header line {
            stroke: #ffffff;
            stroke-width: 1;
        }

        .source-url {
            fill: #fff;
            font-size: 8px;
            font-family: sans-serif;
            text-anchor: middle;
        }
    </style>
    <defs>
        <linearGradient id="header" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#000"/>
            <stop offset="100%" stop-color="#333"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_EX ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#000"/>
            <stop offset="100%" stop-color="#333"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_MEGA ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#8e3628"/>
            <stop offset="100%" stop-color="#c14936"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_LEGENDARY_MEGA ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#6a6278"/>
            <stop offset="100%" stop-color="#898773"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_5 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#3f577c"/>
            <stop offset="100%" stop-color="#6c89b4"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_3 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#806b2e"/>
            <stop offset="100%" stop-color="#b1943f"/>
        </linearGradient>
        <linearGradient class="raidGradient" id="raidBossGradient_<?= RaidBoss::RAID_LEVEL_1 ?>" gradientTransform="rotate(90)">
            <stop offset="0%" stop-color="#870f52"/>
            <stop offset="100%" stop-color="#b7146f"/>
        </linearGradient>
    </defs>

    <g class="graphic-header">
        <rect fill="url('#header')" width="<?=$width?>" height="<?= $graphicHeaderHeight ?>" x="0" y="0"/>
        <line x1="0" x2="<?=$width?>" y1="<?= $graphicHeaderHeight ?>" y2="<?= $graphicHeaderHeight ?>"/>

        <foreignObject xmlns="http://www.w3.org/2000/svg" x="10" y="5" width="<?=$width-20?>" height="<?=$graphicHeaderHeight-25?>">
            <div xmlns="http://www.w3.org/1999/xhtml">
                <?=$translationCollection->getCustomTranslation('raidgraphic_header_description')?>
            </div>
        </foreignObject>

        <g class="title-header">
            <text x="18"  y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_level')?></text>
            <text x="185" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_boss')?></text>
            <text x="335" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_type')?></text>
            <text x="400" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_weather')?></text>
            <text x="470" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_cprange')?></text>
            <text x="590" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_counter')?></text>
            <text x="725" y="<?=$graphicHeaderHeight - 10?>"><?=$translationCollection->getCustomTranslation('raidgraphic_header_difficulty')?></text>
        </g>
    </g>

    <g class="graphic-footer">
        <rect fill="#000" width="<?=$width?>" height="<?= $graphicFooterHeight ?>" x="0" y="<?=$totalHeight-$graphicFooterHeight?>"/>
        <text class="source-url" x="<?=round($width/2)?>" y="<?=$totalHeight-2?>"><?=$translationCollection->getCustomTranslation('raidgraphic_footer_line')?></text>
    </g>

    <?php foreach ($bosses as $index => $boss) : ?>
        <svg id="raidbosswrapper-<?= $boss->getFormId() ?>" x="0" y="<?= $index * $lineHeight + $graphicHeaderHeight ?>" width="100%" height="<?= $lineHeight + 10 ?>">
            <rect fill="url('#raidBossGradient_<?= $boss->getLevel() ?>')" width="100%" height="<?= $lineHeight ?>" x="0" y="0"/>

            <g class="boss-level">
                <rect width="35" height="<?= $lineHeight ?>" x="0" y="0"/>
                <image height="36" width="36" x="0" y="12" href="<?=$boss->getRaidBossEggUrl()?>" />
            </g>

            <g class="boss-name">
                <rect width="215" height="<?= $lineHeight ?>" x="85" y="0"/>
                <?php
                $name = $boss->getSplitBossName(10);
                if ($name->isMultiline()) {
                    $tspan1Class = $name->isFirstLineSmall() ? 'small' : '';
                    $tspan2Class = $name->isFirstLineSmall() ? '' : 'small';
                    ?>
                    <text text-anchor="end" x="295" y="35" class="double-line">
                        <tspan class="<?=$tspan1Class?>" x="295" y="22"><?=$name->getFirstLine()?></tspan><tspan class="<?=$tspan2Class?>" x="295" y="44"><?=$name->getSecondLine()?></tspan>
                    </text>
                <?php } else { ?>
                    <text text-anchor="end" x="295" y="35"><?=$name->getFullName()?></text>
                <?php } ?>
            </g>

            <?php
            $pokemonImage = $boss->getRaidBoss()->getPokemonImage();
            if ($pokemonImage !== null):
            ?>
            <g class="boss-image">
                <rect width="50" height="<?= $lineHeight ?>" x="35" y="0"/>
                <image width="55" height="55" x="25" y="0" href="<?=$pokemonImage->buildUrl($boss->getRaidBoss()->isShinyAvailable() && $raidBossGraphicConfig->useShinyImages())?>"/>
                <?php if ($boss->getRaidBoss()->isShinyAvailable()) : ?>
                    <image class="boss-shiny-image" width="15" height="15" x="22" y="0" href="https://raw.githubusercontent.com/PokeMiners/pogo_assets/master/Images/Filters/ic_shiny_white.png"/>
                <?php endif; ?>
            </g>
            <?php endif; ?>

            <g class="boss-types">
                <rect width="70" height="<?= $lineHeight ?>" x="300" y="0"/>
                <svg width="70" height="<?= $lineHeight?>" x="300" y="0">
                <?php if (count($boss->getTypeNames()) === 1) : ?>
                    <image x="22" y="12" width="26" height="26" class="pokemon-type-icon" href="<?=$boss->getPokemonTypeImageUrl($boss->getTypeNames()[0])?>"></image>
                <?php else : ?>
                    <image x="7" y="12" width="26" height="26" class="pokemon-type-icon"
                           href="<?=$boss->getPokemonTypeImageUrl($boss->getTypeNames()[0])?>">
                    </image>
                    <image x="38" y="12" width="26" height="26" class="pokemon-type-icon"
                           href="<?=$boss->getPokemonTypeImageUrl($boss->getTypeNames()[1])?>">
                    </image>
                <?php endif; ?>
                </svg>
            </g>

            <g class="boss-weather">
                <rect width="60" height="<?= $lineHeight ?>" x="370" y="0"/>
                <svg width="60" height="<?= $lineHeight?>" x="370" y="0">
                    <?php echo $renderWeatherIcon($boss); ?>
                </svg>
            </g>

            <g class="boss-cp-spectrum">
                <rect width="80" height="<?= $lineHeight ?>" x="430" y="0"/>
                <svg width="80" height="<?= $lineHeight?>" x="430" y="0">
                    <text class="normal" x="50%" y="18"><?= $boss->getCpRange()[0] ?>–<?= $boss->getCpRange()[1] ?></text>
                    <text class="boost"  x="50%" y="35"><?= $boss->getCpRangeWeatherBoosted()[0] ?>–<?= $boss->getCpRangeWeatherBoosted()[1] ?></text>
                </svg>
            </g>

            <g class="boss-counter">
                <rect width="160" height="<?= $lineHeight ?>" x="510" y="0"/>
                <svg width="160" height="<?= $lineHeight ?>" x="510" y="0" >
                    <?php
                    $counterTypes = $boss->getEffectiveCounterTypes();
                    $counterTypeIndex = count($counterTypes) - 1;
                    foreach ($boss->getEffectiveCounterTypes() as $type => $multiplier) :
                        $x              = 10 + ($counterTypeIndex * 20) + (($maxCounterInRow - count($counterTypes)) * 10);
                        $multiplierText = str_replace('.', '', $multiplier);
                        ?>
                        <image class="image-counter-<?=$multiplierText?>" x="<?= $x ?>" y="12" width="24" height="24"
                               href="<?=$boss->getPokemonTypeImageUrl($type)?>">
                            <title><?=$type . ' ' . $multiplier?></title>
                        </image>
                        <?php
                        $counterTypeIndex--;
                    endforeach;

                    $counterTypeIndex = count($counterTypes) - 1;
                    foreach ($counterTypes as $type => $multiplier):
                        $x              = 10 + ($counterTypeIndex * 20) + (($maxCounterInRow - count($counterTypes)) * 10);
                        if ($multiplier > 2) : ?>
                            <circle class="double-damage" r="8" cx="<?=$x + 2?>" cy="36" />
                            <text x="<?= $x - 4 ?>" y="39">2x</text>
                        <?php
                        endif;
                        $counterTypeIndex--;
                    endforeach;
                    ?>
                </svg>
            </g>

            <g class="boss-difficulty">
                <rect width="110" height="<?= $lineHeight ?>" x="670" y="0"/>
                <svg width="110" height="<?= $lineHeight?>" x="670" y="0">
                    <?php if (isset($boss->getDifficulty()['hard'])): ?>
                    <g class="mode-hard">
                        <rect rx="5" ry="5" width="30" height="30" x="5" y="10" />
                        <text x="20" y="<?= $lineHeight / 2 ?>"><?php echo $boss->getDifficulty()['hard']?></text>
                    </g>
                    <?php endif; ?>

                    <?php if (isset($boss->getDifficulty()['normal'])): ?>
                    <g class="mode-normal">
                        <rect rx="5" ry="5" width="30" height="30" x="40" y="10" />
                        <text x="55" y="<?= $lineHeight / 2 ?>"><?php echo $boss->getDifficulty()['normal'] ?></text>
                    </g>
                    <?php endif; ?>

                    <?php if (isset($boss->getDifficulty()['easy'])): ?>
                    <g class="mode-easy">
                        <rect rx="5" ry="5" width="30" height="30" x="75" y="10" />
                        <text x="90" y="<?= $lineHeight / 2 ?>"><?php echo $boss->getDifficulty()['easy'] ?></text>
                    </g>
                    <?php endif; ?>
                </svg>
            </g>

        </svg>
    <?php endforeach;
    ?>
</svg>