<?php

declare(strict_types=1);

namespace PokemonGoApi\PogoAPI\Parser;

//phpcs:disable Generic.Files.LineLength.TooLong
class CustomTranslations
{
    public const REGIONAL_PREFIX     = 'regional_form_';
    public const REGIONFORM_ALOLAN   = 'alola';
    public const REGIONFORM_GALARIAN = 'galar';

    /**
     * @return array<string, array<string, string>>
     */
    public static function load(): array
    {
        return [
            TranslationParser::ENGLISH  => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => 'Alolan %s',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => 'Galarian %s',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Players',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::GERMAN   => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => 'Alola-%s',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => 'Galar-%s',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Typen',
                'raidgraphic_header_weather' => 'Wetter',
                'raidgraphic_header_cprange' => 'WP-Spektrum',
                'raidgraphic_header_counter' => 'Konter-Typen',
                'raidgraphic_header_difficulty' => 'Spieleranzahl',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Rot</span> Optimale Level 40 Konter und Beste Freunde Bonus<br/></p>
                    <p><span class="circle mode-normal">Gelb</span> Optimale Level 30 Konter und Hyperfreunde Bonus<br/></p>
                    <p><span class="circle mode-easy">Grün</span> Optimale Level 20 Konter und ohne Freundesbonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::FRENCH   => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => '%s d\'Alola',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => '%s de Galar',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Difficulty',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::ITALIAN  => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => '%s di Alola',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => '%s di Galar',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Difficulty',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::JAPANESE => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => 'アローラ %s',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => 'ガラル %s',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Difficulty',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::KOREAN   => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => '알로라 %s',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => '가라르 %s',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Difficulty',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
            TranslationParser::SPANISH  => [
                self::REGIONAL_PREFIX . self::REGIONFORM_ALOLAN   => '%s de Alola',
                self::REGIONAL_PREFIX . self::REGIONFORM_GALARIAN => '%s de Galar',
                'raidgraphic_header_level' => 'Level',
                'raidgraphic_header_boss' => 'Raidboss',
                'raidgraphic_header_type' => 'Types',
                'raidgraphic_header_weather' => 'Weather',
                'raidgraphic_header_cprange' => 'CP-Range',
                'raidgraphic_header_counter' => 'Counters',
                'raidgraphic_header_difficulty' => 'Difficulty',
                'raidgraphic_header_description' => <<<'HTML'
                    <p><span class="circle mode-hard">Red</span> Optimal lvl 40 Counter and Bestfriends Bonus<br/></p>
                    <p><span class="circle mode-normal">Yellow</span> Optimal lvl 30 Counter and Hyperfriends Bonus<br/></p>
                    <p><span class="circle mode-easy">Green</span> Optimal lvl 20 Counter and without friends Bonus<br/></p>
                    HTML,
                'raidgraphic_footer_line' => 'Raidbosses from leekduck.com | Battleresults from pokebattler.com | Images by The Pokemon Company and Niantic | generated by github.com/pokemon-go-api',
            ],
        ];
    }
}
