openapi: 3.0.0
info:
  title: Pokedex
  version: '1.0'
  description: Pokedex for Pokemon GO
servers:
  - url: 'https://pokemon-go-api.github.io/pokemon-go-api'
tags:
  - name: Pokemon
  - name: Raid
  - name: Utils
  - name: Quest
paths:
  /api/pokedex.json:
    get:
      operationId: get-api-pokedex.json
      description: A full list of all Pokemon available in Pokemon GO
      summary: A full list of all Pokemon available in Pokemon GO
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
                additionalProperties: false
  /api/pokedex/mega.json:
    get:
      operationId: get-api-pokedex-mega.json
      description: List of all available Mega Pokemon
      summary: List of all available Mega Pokemon
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
                required:
                  - items
                additionalProperties: false
  '/api/pokedex/generation/{generationNumber}.json':
    get:
      operationId: get-api-pokedex-generation-id.json
      description: List all Pokemon in the given generation number
      summary: List all Pokemon in the given generation number
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
                required:
                  - items
                additionalProperties: false
    parameters:
      - schema:
          type: number
        name: generationNumber
        in: path
        required: true
  '/api/pokedex/id/{id}.json':
    get:
      operationId: get-api-pokedex-id-id.json
      description: Receive a single Pokemon by the Pokedex number
      summary: Receive a single Pokemon by the Pokedex number
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
  '/api/pokedex/region/{name}.json':
    get:
      operationId: get-api-pokedex-region-name.json
      description: Receive all available Pokemon in the given region
      summary: Receive all available Pokemon in the given region
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pokemon'
                required:
                  - items
                additionalProperties: false
    parameters:
      - schema:
          type: string
          enum:
            - alola
            - galarian
        name: name
        in: path
        required: true
  '/api/pokedex/name/{name}.json':
    get:
      operationId: get-api-pokedex-name-name.json
      description: Receive a single Pokemon by the PokemonGo internal name in UPPERCASE
      summary: Receive a single Pokemon by the PokemonGo internal name in UPPERCASE
      tags:
        - Pokemon
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pokemon'
    parameters:
      - schema:
          type: string
        name: name
        in: path
        required: true
  /api/raidboss.json:
    get:
      operationId: get-api-raidboss.json
      description: Return the current raid bosses
      summary: Receive the current raid Bosses
      tags:
        - Raid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                additionalProperties: false
                properties:
                  currentList:
                    type: object
                    required:
                      - lvl1
                      - lvl3
                      - lvl5
                      - mega
                    additionalProperties: false
                    properties:
                      lvl1:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          $ref: '#/components/schemas/RaidBoss'
                      lvl3:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          $ref: '#/components/schemas/RaidBoss'
                      lvl5:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          $ref: '#/components/schemas/RaidBoss'
                      mega:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          $ref: '#/components/schemas/RaidBoss'
                      ex:
                        type: array
                        items:
                          $ref: '#/components/schemas/RaidBoss'
                  graphics:
                    type: object
                    required:
                      - German
                      - English
                    additionalProperties: false
                    properties:
                      German:
                        type: object
                        required:
                          - svg
                          - png
                          - sha512
                        additionalProperties: false
                        properties:
                          svg:
                            type: string
                          png:
                            type: string
                          sha512:
                            type: string
                      English:
                        type: object
                        required:
                          - svg
                          - png
                          - sha512
                        additionalProperties: false
                        properties:
                          svg:
                            type: string
                          png:
                            type: string
                          sha512:
                            type: string
                required:
                  - currentList
                  - graphics
  /api/hashes.json:
    get:
      operationId: get-api-hashes.json
      description: Receive the latest hashes of the endpoints to prevent unnessecary calls to larger API Endpoints
      summary: Return the hashes of the latest generated API resources to avoid unnecessary calls
      tags:
        - Utils
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                additionalProperties: false
                properties:
                  sha512:
                    type: object
                    required:
                      - raidboss.json
                      - pokedex.json
                      - quests.json
                    additionalProperties: false
                    properties:
                      raidboss.json:
                        type: string
                        minLength: 128
                        maxLength: 128
                      quests.json:
                        type: string
                        minLength: 128
                        maxLength: 128
                      pokedex.json:
                        type: string
                        minLength: 128
                        maxLength: 128
                required:
                  - sha512
  /api/quests.json:
    get:
      summary: Receive the current Quest List with Pokemon rewards only
      tags:
        - Pokemon
        - Quest
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                uniqueItems: true
                items:
                  type: object
                  additionalProperties: false
                  properties:
                    rewards:
                      type: array
                      uniqueItems: true
                      items:
                        $ref: '#/components/schemas/Encounter'
                    quest:
                      $ref: '#/components/schemas/Names'
                  required:
                    - rewards
                    - quest
      operationId: get-quests.json
    parameters: []
components:
  schemas:
    Pokemon:
      description: ''
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          minLength: 1
        formId:
          type: string
          minLength: 1
        dexNr:
          type: integer
          minimum: 1
        generation:
          type: integer
        names:
          $ref: '#/components/schemas/Names'
        stats:
          oneOf:
            - $ref: '#/components/schemas/PokemonStats'
          nullable: true
        primaryType:
          $ref: '#/components/schemas/Type'
        secondaryType:
          oneOf:
            - $ref: '#/components/schemas/Type'
          nullable: true
        quickMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        cinematicMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        eliteQuickMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        eliteCinematicMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        assets:
          $ref: '#/components/schemas/Assets'
        assetForms:
          type: array
          items:
            $ref: '#/components/schemas/Assets'
        regionForms:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/RegionPokemon'
        hasMegaEvolution:
          type: boolean
        megaEvolutions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MegaEvolution'
      required:
        - id
        - formId
        - dexNr
        - generation
        - names
        - stats
        - primaryType
        - secondaryType
        - quickMoves
        - cinematicMoves
        - eliteQuickMoves
        - eliteCinematicMoves
        - assets
        - assetForms
        - regionForms
        - hasMegaEvolution
        - megaEvolutions
    RegionPokemon:
      description: ''
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        formId:
          type: string
          minLength: 1
        dexNr:
          type: integer
        generation:
          type: integer
        names:
          $ref: '#/components/schemas/Names'
        stats:
          oneOf:
            - $ref: '#/components/schemas/PokemonStats'
          nullable: true
        primaryType:
          $ref: '#/components/schemas/Type'
        secondaryType:
          oneOf:
            - $ref: '#/components/schemas/Type'
          nullable: true
        quickMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        cinematicMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        eliteQuickMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        eliteCinematicMoves:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PokemonMove'
        assets:
          $ref: '#/components/schemas/Assets'
        regionForms:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/RegionPokemon'
        hasMegaEvolution:
          type: boolean
        megaEvolutions:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/MegaEvolution'
      required:
        - id
        - formId
        - dexNr
        - generation
        - names
        - stats
        - primaryType
        - secondaryType
        - quickMoves
        - cinematicMoves
        - eliteQuickMoves
        - eliteCinematicMoves
        - assets
        - regionForms
        - hasMegaEvolution
        - megaEvolutions
    Names:
      description: ''
      type: object
      additionalProperties: false
      properties:
        English:
          type: string
        German:
          type: string
        French:
          type: string
        Italian:
          type: string
        Japanese:
          type: string
        Korean:
          type: string
        Spanish:
          type: string
      required:
        - English
        - German
    Type:
      description: ''
      type: object
      required:
        - type
        - names
      additionalProperties: false
      properties:
        type:
          type: string
          minLength: 1
        names:
          $ref: '#/components/schemas/Names'
    PokemonStats:
      description: ''
      type: object
      additionalProperties: false
      properties:
        stamina:
          type: integer
        attack:
          type: integer
        defense:
          type: integer
      required:
        - stamina
        - attack
        - defense
    PokemonMove:
      description: ''
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          minLength: 1
        power:
          type: number
        energy:
          type: number
        durationMs:
          type: number
        type:
          $ref: '#/components/schemas/Type'
        names:
          $ref: '#/components/schemas/Names'
        combat:
          type: object
          additionalProperties: false
          required:
            - energy
            - power
            - turns
            - buffs
          nullable: true
          properties:
            energy:
              type: number
            power:
              type: number
            turns:
              type: number
            buffs:
              type: object
              additionalProperties: false
              required:
                - activationChance
                - attackerAttackStatsChange
                - attackerDefenseStatsChange
                - targetAttackStatsChange
                - targetDefenseStatsChange
              nullable: true
              properties:
                activationChance:
                  type: integer
                attackerAttackStatsChange:
                  type: integer
                  nullable: true
                attackerDefenseStatsChange:
                  type: integer
                  nullable: true
                targetAttackStatsChange:
                  type: integer
                  nullable: true
                targetDefenseStatsChange:
                  type: integer
                  nullable: true
      required:
        - id
        - power
        - energy
        - durationMs
        - type
        - names
        - combat
    Assets:
      title: Assets
      type: object
      additionalProperties: false
      properties:
        image:
          type: string
          format: uri
        shinyImage:
          type: string
          format: uri
      required:
        - image
        - shinyImage
    MegaEvolution:
      title: MegaEvolution
      type: object
      required:
        - id
        - names
        - stats
        - primaryType
        - secondaryType
        - assets
      additionalProperties: false
      properties:
        id:
          type: string
          minLength: 1
        names:
          $ref: '#/components/schemas/Names'
        stats:
          $ref: '#/components/schemas/PokemonStats'
        primaryType:
          $ref: '#/components/schemas/Type'
        secondaryType:
          oneOf:
            - $ref: '#/components/schemas/Type'
          nullable: true
        assets:
          $ref: '#/components/schemas/Assets'
    RaidBoss:
      description: ''
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
        form:
          type: string
        assets:
          $ref: '#/components/schemas/Assets'
        level:
          type: string
          enum:
            - ex
            - mega
            - lvl5
            - lvl3
            - lvl1
        shiny:
          type: boolean
        types:
          type: array
          uniqueItems: true
          minItems: 1
          maxItems: 2
          items:
            type: string
        counter:
          type: object
          additionalProperties:
            type: number
        weather:
          type: array
          minItems: 1
          maxItems: 2
          items:
            type: string
        cpRange:
          $ref: '#/components/schemas/CpRange'
        cpRangeBoost:
          $ref: '#/components/schemas/CpRange'
        names:
          $ref: '#/components/schemas/Names'
        battleResult:
          type: object
          properties:
            easy:
              $ref: '#/components/schemas/BattleResult'
            normal:
              $ref: '#/components/schemas/BattleResult'
            hard:
              $ref: '#/components/schemas/BattleResult'
          additionalProperties: false
          required:
            - easy
            - normal
            - hard
      required:
        - id
        - form
        - assets
        - level
        - shiny
        - types
        - counter
        - weather
        - cpRange
        - cpRangeBoost
        - names
        - battleResult
    BattleResult:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        friendshipLevel:
          type: integer
          minimum: 0
          maximum: 4
        pokemonLevel:
          type: integer
          minimum: 0
          maximum: 50
        totalEstimator:
          type: number
          format: double
          minimum: 0
          maximum: 20
      required:
        - name
        - friendshipLevel
        - pokemonLevel
        - totalEstimator
    CpRange:
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: integer
        minimum: 0
    Encounter:
      type: object
      title: Encounter
      additionalProperties: false
      properties:
        id:
          type: string
        shiny:
          type: boolean
        cpRange:
          $ref: '#/components/schemas/CpRange'
        assets:
          $ref: '#/components/schemas/Assets'
        name:
          $ref: '#/components/schemas/Names'
      required:
        - id
        - shiny
        - cpRange
        - assets
        - name
